num_cams = 2,               // number of cameras we use
num_cams_actual = 4,        // number of cameras actually available in dataset
lkt_window = 21,
lkt_pyramid = 4,
corner_count = 3000,        // number of features
icp_skip = 200,
f2f_iterations = 2,
icp_iterations = 3,
min_matches = 0,            // minimum number of feature matches to proceed
detect_every = 1,           // detect new features every this number of frames
ba_every = 10,              // bundle adjust every this number of frames
ndiagonal = 4;

flow_outlier = 20000,       // pixels^2, squared distance of optical flow
quality_level = 0.001,      // good features to track quality
min_distance = 12,          // pixel distance between nearest features
weight_3D2D = 10,
weight_2D2D = 500,
weight_3DPD = 1,            // there are more of them
loss_thresh_3D2D = 0.01,    // reprojection error, canonical camera units
loss_thresh_2D2D = 0.00002,
loss_thresh_3DPD = 0.1,     // physical distance, meters
loss_thresh_3D3D = 0.04,    // physical distance, meters
match_thresh = 29,          // bits, hamming distance for FREAK features
depth_assoc_thresh = 0.015, // canonical camera units
z_weight = 0.6,
outlier_reject = 5.0,
correspondence_thresh_icp = 0.5,
icp_norm_condition = 1e-5,
agreement_t_thresh = 0.1,   // meters
agreement_r_thresh = 0.05,  // radians
loop_close_thresh = 10;     // meters

img_width = 1226,           // kitti data
img_height = 370;