%YAML:1.0
# dataset_dir
dataset_dir: ./data/kitti/odometry/dataset/sequences/00

save_predicted_traj_to: ./result/cam_traj_00.txt

# VO Parameters

# ------------------- Feature Matching -------------------
# ORB settings
number_of_features: 10000
scale_factor: 1.2
level_pyramid: 8
score_threshold: 20
match_ratio: 2.0

# ------------------- RANSAC Essential matrix -------------------
findEssentialMat_prob: 0.999
findEssentialMat_threshold: 1.0

# ------------------- Triangulation -------------------
min_triang_angle: 1.0
max_ratio_between_max_angle_and_median_angle: 20
initialization_sigma: 1.0

# ------------------- Initialization -------------------
min_inlier_matches: 15

# ------------------- Tracking -------------------
min_dist_between_two_keyframes: 1.0
min_rotation_angle_betwen_two_keyframes: 0.5

# ------------------- Bundle Adjustment -------------------
is_ba_fix_map_points: true